### ISSUE TITLE
cleanup.py is failing on domains which are not running

### ISSUE THREAD

**Issue by nhlfr** [Mirantis/virtlet#34]
```
docker exec -ti dockercompose_libvirt_1 /cleanup.py                                                              
Cleaning up VMs
Destroying VM cirros
libvirt: QEMU Driver error : Requested operation is not valid: domain is not running
Traceback (most recent call last):
  File "/cleanup.py", line 61, in <module>
    main()
  File "/cleanup.py", line 33, in main
    if domain.destroy() < 0:
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1103, in destroy
    if ret == -1: raise libvirtError ('virDomainDestroy() failed', dom=self)
libvirt.libvirtError: Requested operation is not valid: domain is not running
```

**Comment by jellonek** [comment]
Can you start virtlet (it will spam you with errors) and then try to run this command?

**Comment by nhlfr** [comment]
sure
