### ISSUE TITLE
Virtlet fix volume creation issues

### ISSUE THREAD

**Issue by vefimova** [Mirantis/virtlet#66]
Virtlet crashes with following backtrace due to volume name is null:

```
virtlet_1  | panic: runtime error: invalid memory address or nil pointer dereference
virtlet_1  | [signal 0xb code=0x1 addr=0x0 pc=0x555201]
virtlet_1  |
virtlet_1  | goroutine 76 [running]:
virtlet_1  | panic(0xa3e720, 0xc820010080)
virtlet_1  |    /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
virtlet_1  | github.com/Mirantis/virtlet/pkg/libvirttools.(*VirtualizationTool).processVolumes(0xc8201ee450, 0xc82005a420, 0x1, 0x1, 0xc82005dc00, 0x3fc, 0x0, 0x0, 0x0, 0x0)
virtlet_1  |    /go/src/github.com/Mirantis/virtlet/pkg/libvirttools/virtualization.go:145 +0x481
virtlet_1  | github.com/Mirantis/virtlet/pkg/libvirttools.(*VirtualizationTool).CreateContainer(0xc8201ee450, 0xc82040a0c0, 0xc8203ccc40, 0x1e, 0x0, 0x0, 0x0, 0x0)
virtlet_1  |    /go/src/github.com/Mirantis/virtlet/pkg/libvirttools/virtualization.go:267 +0x289
virtlet_1  | github.com/Mirantis/virtlet/pkg/manager.(*VirtletManager).CreateContainer(0xc8201ee600, 0x7f01eb9a5758, 0xc82040a060, 0xc82040a0c0, 0x0, 0x0, 0x0)
virtlet_1  |    /go/src/github.com/Mirantis/virtlet/pkg/manager/manager.go:174 +0x151
virtlet_1  | github.com/Mirantis/virtlet/vendor/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime._RuntimeService_CreateContainer_Handler(0xae4b40, 0xc8201ee600, 0x7f01eb9a5758, 0xc82040a060, 0xc8203ce0a0, 0x0, 0x0, 0x0, 0x0, 0x0)
```

In latest master Volume names were removed completly:
https://github.com/kubernetes/kubernetes/pull/33970

**Comment by vefimova** [comment]
So now we need to generate volume names by our own. Need to check:
- Volume name must be unique across host
- Make a list of additional internal-usage volumes created by kubelet, what are they, what are they purposes, how to handle persistency if needed?

**Comment by vefimova** [comment]
check workability using the following pod definition:
Pod specification:
apiVersion: v1
kind: Pod
metadata:
 name: test-vm-cirros
spec:
 containers:
 - name: test-vm-cirros
    image: download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
 volumeMounts:
  - mountPath: /test-dir-1
     name: test-volume-1
  - mountPath: /test-dir-2
     name: test-volume-2
volumes:
- name: test-volume-1
  hostPath:
    path: /var/lib/virtlet/volume1
- name: test-volume-2
  hostPath:
    path: /var/lib/virtlet/volume2
